repos:
  - repo: local
    hooks:
      - id: js-beautify-html
        name: js-beautify (HTML)
        entry: js-beautify --type html --replace
        language: node
        additional_dependencies: ["js-beautify@1.15.1"]
        files: '\.(html|htm)$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: '\.(html|htm)$'   # <-- don’t touch HTML
      - id: trailing-whitespace
