# .github/workflows/sitemap.yml
name: Generate sitemap
on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    # avoid action pushing a change that retriggers itself
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for correct <lastmod> dates

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://ashish96puri.github.io/"
          drop-html-extension: true  # if you prefer /page/ over /page.html

      - name: Commit sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || exit 0
          git push
